// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game_messages.proto
// Protobuf C++ Version: 5.29.2

#include "game_messages.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace game {

inline constexpr Pos::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Pos::Pos(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PosDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PosDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PosDefaultTypeInternal() {}
  union {
    Pos _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PosDefaultTypeInternal _Pos_default_instance_;

inline constexpr CG_LOGIN_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : username_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR CG_LOGIN_REQ::CG_LOGIN_REQ(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CG_LOGIN_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CG_LOGIN_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CG_LOGIN_REQDefaultTypeInternal() {}
  union {
    CG_LOGIN_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CG_LOGIN_REQDefaultTypeInternal _CG_LOGIN_REQ_default_instance_;

inline constexpr GC_MOVE_NOTIFY::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cur_pos_{nullptr},
        move_pos_{nullptr},
        player_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GC_MOVE_NOTIFY::GC_MOVE_NOTIFY(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GC_MOVE_NOTIFYDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GC_MOVE_NOTIFYDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GC_MOVE_NOTIFYDefaultTypeInternal() {}
  union {
    GC_MOVE_NOTIFY _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GC_MOVE_NOTIFYDefaultTypeInternal _GC_MOVE_NOTIFY_default_instance_;

inline constexpr GC_LOGIN_RES::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        spawn_pos_{nullptr},
        success_{false},
        player_id_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GC_LOGIN_RES::GC_LOGIN_RES(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GC_LOGIN_RESDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GC_LOGIN_RESDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GC_LOGIN_RESDefaultTypeInternal() {}
  union {
    GC_LOGIN_RES _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GC_LOGIN_RESDefaultTypeInternal _GC_LOGIN_RES_default_instance_;

inline constexpr CG_MOVE_REQ::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        cur_pos_{nullptr},
        move_pos_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR CG_MOVE_REQ::CG_MOVE_REQ(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CG_MOVE_REQDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CG_MOVE_REQDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CG_MOVE_REQDefaultTypeInternal() {}
  union {
    CG_MOVE_REQ _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CG_MOVE_REQDefaultTypeInternal _CG_MOVE_REQ_default_instance_;
}  // namespace game
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_game_5fmessages_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_game_5fmessages_2eproto = nullptr;
const ::uint32_t
    TableStruct_game_5fmessages_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::game::Pos, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::Pos, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::game::Pos, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::game::Pos, _impl_.z_),
        PROTOBUF_FIELD_OFFSET(::game::CG_MOVE_REQ, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::game::CG_MOVE_REQ, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::CG_MOVE_REQ, _impl_.cur_pos_),
        PROTOBUF_FIELD_OFFSET(::game::CG_MOVE_REQ, _impl_.move_pos_),
        0,
        1,
        PROTOBUF_FIELD_OFFSET(::game::GC_MOVE_NOTIFY, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::game::GC_MOVE_NOTIFY, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::GC_MOVE_NOTIFY, _impl_.player_id_),
        PROTOBUF_FIELD_OFFSET(::game::GC_MOVE_NOTIFY, _impl_.cur_pos_),
        PROTOBUF_FIELD_OFFSET(::game::GC_MOVE_NOTIFY, _impl_.move_pos_),
        ~0u,
        0,
        1,
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::game::CG_LOGIN_REQ, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::CG_LOGIN_REQ, _impl_.username_),
        PROTOBUF_FIELD_OFFSET(::game::GC_LOGIN_RES, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::game::GC_LOGIN_RES, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::game::GC_LOGIN_RES, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::game::GC_LOGIN_RES, _impl_.player_id_),
        PROTOBUF_FIELD_OFFSET(::game::GC_LOGIN_RES, _impl_.spawn_pos_),
        ~0u,
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::game::Pos)},
        {11, 21, -1, sizeof(::game::CG_MOVE_REQ)},
        {23, 34, -1, sizeof(::game::GC_MOVE_NOTIFY)},
        {37, -1, -1, sizeof(::game::CG_LOGIN_REQ)},
        {46, 57, -1, sizeof(::game::GC_LOGIN_RES)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::game::_Pos_default_instance_._instance,
    &::game::_CG_MOVE_REQ_default_instance_._instance,
    &::game::_GC_MOVE_NOTIFY_default_instance_._instance,
    &::game::_CG_LOGIN_REQ_default_instance_._instance,
    &::game::_GC_LOGIN_RES_default_instance_._instance,
};
const char descriptor_table_protodef_game_5fmessages_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023game_messages.proto\022\004game\"&\n\003Pos\022\t\n\001x\030"
    "\001 \001(\002\022\t\n\001y\030\002 \001(\002\022\t\n\001z\030\003 \001(\002\"F\n\013CG_MOVE_R"
    "EQ\022\032\n\007cur_pos\030\001 \001(\0132\t.game.Pos\022\033\n\010move_p"
    "os\030\002 \001(\0132\t.game.Pos\"\\\n\016GC_MOVE_NOTIFY\022\021\n"
    "\tplayer_id\030\001 \001(\005\022\032\n\007cur_pos\030\002 \001(\0132\t.game"
    ".Pos\022\033\n\010move_pos\030\003 \001(\0132\t.game.Pos\" \n\014CG_"
    "LOGIN_REQ\022\020\n\010username\030\001 \001(\t\"P\n\014GC_LOGIN_"
    "RES\022\017\n\007success\030\001 \001(\010\022\021\n\tplayer_id\030\002 \001(\005\022"
    "\034\n\tspawn_pos\030\003 \001(\0132\t.game.Posb\006proto3"
};
static ::absl::once_flag descriptor_table_game_5fmessages_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_game_5fmessages_2eproto = {
    false,
    false,
    357,
    descriptor_table_protodef_game_5fmessages_2eproto,
    "game_messages.proto",
    &descriptor_table_game_5fmessages_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_game_5fmessages_2eproto::offsets,
    file_level_enum_descriptors_game_5fmessages_2eproto,
    file_level_service_descriptors_game_5fmessages_2eproto,
};
namespace game {
// ===================================================================

class Pos::_Internal {
 public:
};

Pos::Pos(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.Pos)
}
Pos::Pos(
    ::google::protobuf::Arena* arena, const Pos& from)
    : Pos(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Pos::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Pos::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, z_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::z_));
}
Pos::~Pos() {
  // @@protoc_insertion_point(destructor:game.Pos)
  SharedDtor(*this);
}
inline void Pos::SharedDtor(MessageLite& self) {
  Pos& this_ = static_cast<Pos&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* Pos::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Pos(arena);
}
constexpr auto Pos::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Pos),
                                            alignof(Pos));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Pos::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Pos_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Pos::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Pos>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Pos::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Pos>(), &Pos::ByteSizeLong,
            &Pos::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Pos, _impl_._cached_size_),
        false,
    },
    &Pos::kDescriptorMethods,
    &descriptor_table_game_5fmessages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Pos::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Pos::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::Pos>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // float x = 1;
    {::_pbi::TcParser::FastF32S1,
     {13, 63, 0, PROTOBUF_FIELD_OFFSET(Pos, _impl_.x_)}},
    // float y = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(Pos, _impl_.y_)}},
    // float z = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(Pos, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // float x = 1;
    {PROTOBUF_FIELD_OFFSET(Pos, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 2;
    {PROTOBUF_FIELD_OFFSET(Pos, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float z = 3;
    {PROTOBUF_FIELD_OFFSET(Pos, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Pos::Clear() {
// @@protoc_insertion_point(message_clear_start:game.Pos)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.z_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.z_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Pos::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Pos& this_ = static_cast<const Pos&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Pos::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Pos& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.Pos)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // float x = 1;
          if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                1, this_._internal_x(), target);
          }

          // float y = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_y(), target);
          }

          // float z = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_z(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.Pos)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Pos::ByteSizeLong(const MessageLite& base) {
          const Pos& this_ = static_cast<const Pos&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Pos::ByteSizeLong() const {
          const Pos& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.Pos)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // float x = 1;
            if (::absl::bit_cast<::uint32_t>(this_._internal_x()) != 0) {
              total_size += 5;
            }
            // float y = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_y()) != 0) {
              total_size += 5;
            }
            // float z = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_z()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Pos::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Pos*>(&to_msg);
  auto& from = static_cast<const Pos&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game.Pos)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint32_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Pos::CopyFrom(const Pos& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.Pos)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Pos::InternalSwap(Pos* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Pos, _impl_.z_)
      + sizeof(Pos::_impl_.z_)
      - PROTOBUF_FIELD_OFFSET(Pos, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Pos::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CG_MOVE_REQ::_Internal {
 public:
  using HasBits =
      decltype(std::declval<CG_MOVE_REQ>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_._has_bits_);
};

CG_MOVE_REQ::CG_MOVE_REQ(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.CG_MOVE_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CG_MOVE_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::CG_MOVE_REQ& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

CG_MOVE_REQ::CG_MOVE_REQ(
    ::google::protobuf::Arena* arena,
    const CG_MOVE_REQ& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CG_MOVE_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.cur_pos_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::game::Pos>(
                              arena, *from._impl_.cur_pos_)
                        : nullptr;
  _impl_.move_pos_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::game::Pos>(
                              arena, *from._impl_.move_pos_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:game.CG_MOVE_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CG_MOVE_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void CG_MOVE_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cur_pos_),
           0,
           offsetof(Impl_, move_pos_) -
               offsetof(Impl_, cur_pos_) +
               sizeof(Impl_::move_pos_));
}
CG_MOVE_REQ::~CG_MOVE_REQ() {
  // @@protoc_insertion_point(destructor:game.CG_MOVE_REQ)
  SharedDtor(*this);
}
inline void CG_MOVE_REQ::SharedDtor(MessageLite& self) {
  CG_MOVE_REQ& this_ = static_cast<CG_MOVE_REQ&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.cur_pos_;
  delete this_._impl_.move_pos_;
  this_._impl_.~Impl_();
}

inline void* CG_MOVE_REQ::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CG_MOVE_REQ(arena);
}
constexpr auto CG_MOVE_REQ::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CG_MOVE_REQ),
                                            alignof(CG_MOVE_REQ));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CG_MOVE_REQ::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CG_MOVE_REQ_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CG_MOVE_REQ::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CG_MOVE_REQ>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CG_MOVE_REQ::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CG_MOVE_REQ>(), &CG_MOVE_REQ::ByteSizeLong,
            &CG_MOVE_REQ::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_._cached_size_),
        false,
    },
    &CG_MOVE_REQ::kDescriptorMethods,
    &descriptor_table_game_5fmessages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CG_MOVE_REQ::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 2, 0, 2> CG_MOVE_REQ::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_._has_bits_),
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::CG_MOVE_REQ>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // .game.Pos move_pos = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 1, 1, PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_.move_pos_)}},
    // .game.Pos cur_pos = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_.cur_pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .game.Pos cur_pos = 1;
    {PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_.cur_pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .game.Pos move_pos = 2;
    {PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_.move_pos_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game::Pos>()},
    {::_pbi::TcParser::GetTable<::game::Pos>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void CG_MOVE_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:game.CG_MOVE_REQ)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.cur_pos_ != nullptr);
      _impl_.cur_pos_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.move_pos_ != nullptr);
      _impl_.move_pos_->Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CG_MOVE_REQ::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CG_MOVE_REQ& this_ = static_cast<const CG_MOVE_REQ&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CG_MOVE_REQ::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CG_MOVE_REQ& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.CG_MOVE_REQ)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .game.Pos cur_pos = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.cur_pos_, this_._impl_.cur_pos_->GetCachedSize(), target,
                stream);
          }

          // .game.Pos move_pos = 2;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.move_pos_, this_._impl_.move_pos_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.CG_MOVE_REQ)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CG_MOVE_REQ::ByteSizeLong(const MessageLite& base) {
          const CG_MOVE_REQ& this_ = static_cast<const CG_MOVE_REQ&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CG_MOVE_REQ::ByteSizeLong() const {
          const CG_MOVE_REQ& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.CG_MOVE_REQ)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .game.Pos cur_pos = 1;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cur_pos_);
            }
            // .game.Pos move_pos = 2;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.move_pos_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CG_MOVE_REQ::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CG_MOVE_REQ*>(&to_msg);
  auto& from = static_cast<const CG_MOVE_REQ&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:game.CG_MOVE_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.cur_pos_ != nullptr);
      if (_this->_impl_.cur_pos_ == nullptr) {
        _this->_impl_.cur_pos_ =
            ::google::protobuf::Message::CopyConstruct<::game::Pos>(arena, *from._impl_.cur_pos_);
      } else {
        _this->_impl_.cur_pos_->MergeFrom(*from._impl_.cur_pos_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.move_pos_ != nullptr);
      if (_this->_impl_.move_pos_ == nullptr) {
        _this->_impl_.move_pos_ =
            ::google::protobuf::Message::CopyConstruct<::game::Pos>(arena, *from._impl_.move_pos_);
      } else {
        _this->_impl_.move_pos_->MergeFrom(*from._impl_.move_pos_);
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CG_MOVE_REQ::CopyFrom(const CG_MOVE_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.CG_MOVE_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CG_MOVE_REQ::InternalSwap(CG_MOVE_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_.move_pos_)
      + sizeof(CG_MOVE_REQ::_impl_.move_pos_)
      - PROTOBUF_FIELD_OFFSET(CG_MOVE_REQ, _impl_.cur_pos_)>(
          reinterpret_cast<char*>(&_impl_.cur_pos_),
          reinterpret_cast<char*>(&other->_impl_.cur_pos_));
}

::google::protobuf::Metadata CG_MOVE_REQ::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GC_MOVE_NOTIFY::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GC_MOVE_NOTIFY>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_._has_bits_);
};

GC_MOVE_NOTIFY::GC_MOVE_NOTIFY(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.GC_MOVE_NOTIFY)
}
inline PROTOBUF_NDEBUG_INLINE GC_MOVE_NOTIFY::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::GC_MOVE_NOTIFY& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GC_MOVE_NOTIFY::GC_MOVE_NOTIFY(
    ::google::protobuf::Arena* arena,
    const GC_MOVE_NOTIFY& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GC_MOVE_NOTIFY* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.cur_pos_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::game::Pos>(
                              arena, *from._impl_.cur_pos_)
                        : nullptr;
  _impl_.move_pos_ = (cached_has_bits & 0x00000002u) ? ::google::protobuf::Message::CopyConstruct<::game::Pos>(
                              arena, *from._impl_.move_pos_)
                        : nullptr;
  _impl_.player_id_ = from._impl_.player_id_;

  // @@protoc_insertion_point(copy_constructor:game.GC_MOVE_NOTIFY)
}
inline PROTOBUF_NDEBUG_INLINE GC_MOVE_NOTIFY::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GC_MOVE_NOTIFY::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, cur_pos_),
           0,
           offsetof(Impl_, player_id_) -
               offsetof(Impl_, cur_pos_) +
               sizeof(Impl_::player_id_));
}
GC_MOVE_NOTIFY::~GC_MOVE_NOTIFY() {
  // @@protoc_insertion_point(destructor:game.GC_MOVE_NOTIFY)
  SharedDtor(*this);
}
inline void GC_MOVE_NOTIFY::SharedDtor(MessageLite& self) {
  GC_MOVE_NOTIFY& this_ = static_cast<GC_MOVE_NOTIFY&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.cur_pos_;
  delete this_._impl_.move_pos_;
  this_._impl_.~Impl_();
}

inline void* GC_MOVE_NOTIFY::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GC_MOVE_NOTIFY(arena);
}
constexpr auto GC_MOVE_NOTIFY::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GC_MOVE_NOTIFY),
                                            alignof(GC_MOVE_NOTIFY));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GC_MOVE_NOTIFY::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GC_MOVE_NOTIFY_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GC_MOVE_NOTIFY::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GC_MOVE_NOTIFY>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GC_MOVE_NOTIFY::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GC_MOVE_NOTIFY>(), &GC_MOVE_NOTIFY::ByteSizeLong,
            &GC_MOVE_NOTIFY::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_._cached_size_),
        false,
    },
    &GC_MOVE_NOTIFY::kDescriptorMethods,
    &descriptor_table_game_5fmessages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GC_MOVE_NOTIFY::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 2, 0, 2> GC_MOVE_NOTIFY::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    2,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::GC_MOVE_NOTIFY>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // int32 player_id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GC_MOVE_NOTIFY, _impl_.player_id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.player_id_)}},
    // .game.Pos cur_pos = 2;
    {::_pbi::TcParser::FastMtS1,
     {18, 0, 0, PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.cur_pos_)}},
    // .game.Pos move_pos = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 1, 1, PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.move_pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 player_id = 1;
    {PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.player_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .game.Pos cur_pos = 2;
    {PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.cur_pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // .game.Pos move_pos = 3;
    {PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.move_pos_), _Internal::kHasBitsOffset + 1, 1,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game::Pos>()},
    {::_pbi::TcParser::GetTable<::game::Pos>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GC_MOVE_NOTIFY::Clear() {
// @@protoc_insertion_point(message_clear_start:game.GC_MOVE_NOTIFY)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(_impl_.cur_pos_ != nullptr);
      _impl_.cur_pos_->Clear();
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(_impl_.move_pos_ != nullptr);
      _impl_.move_pos_->Clear();
    }
  }
  _impl_.player_id_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GC_MOVE_NOTIFY::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GC_MOVE_NOTIFY& this_ = static_cast<const GC_MOVE_NOTIFY&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GC_MOVE_NOTIFY::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GC_MOVE_NOTIFY& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.GC_MOVE_NOTIFY)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 player_id = 1;
          if (this_._internal_player_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_player_id(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .game.Pos cur_pos = 2;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                2, *this_._impl_.cur_pos_, this_._impl_.cur_pos_->GetCachedSize(), target,
                stream);
          }

          // .game.Pos move_pos = 3;
          if (cached_has_bits & 0x00000002u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.move_pos_, this_._impl_.move_pos_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.GC_MOVE_NOTIFY)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GC_MOVE_NOTIFY::ByteSizeLong(const MessageLite& base) {
          const GC_MOVE_NOTIFY& this_ = static_cast<const GC_MOVE_NOTIFY&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GC_MOVE_NOTIFY::ByteSizeLong() const {
          const GC_MOVE_NOTIFY& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.GC_MOVE_NOTIFY)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
          cached_has_bits = this_._impl_._has_bits_[0];
          if (cached_has_bits & 0x00000003u) {
            // .game.Pos cur_pos = 2;
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.cur_pos_);
            }
            // .game.Pos move_pos = 3;
            if (cached_has_bits & 0x00000002u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.move_pos_);
            }
          }
           {
            // int32 player_id = 1;
            if (this_._internal_player_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_player_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GC_MOVE_NOTIFY::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GC_MOVE_NOTIFY*>(&to_msg);
  auto& from = static_cast<const GC_MOVE_NOTIFY&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:game.GC_MOVE_NOTIFY)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000003u) {
    if (cached_has_bits & 0x00000001u) {
      ABSL_DCHECK(from._impl_.cur_pos_ != nullptr);
      if (_this->_impl_.cur_pos_ == nullptr) {
        _this->_impl_.cur_pos_ =
            ::google::protobuf::Message::CopyConstruct<::game::Pos>(arena, *from._impl_.cur_pos_);
      } else {
        _this->_impl_.cur_pos_->MergeFrom(*from._impl_.cur_pos_);
      }
    }
    if (cached_has_bits & 0x00000002u) {
      ABSL_DCHECK(from._impl_.move_pos_ != nullptr);
      if (_this->_impl_.move_pos_ == nullptr) {
        _this->_impl_.move_pos_ =
            ::google::protobuf::Message::CopyConstruct<::game::Pos>(arena, *from._impl_.move_pos_);
      } else {
        _this->_impl_.move_pos_->MergeFrom(*from._impl_.move_pos_);
      }
    }
  }
  if (from._internal_player_id() != 0) {
    _this->_impl_.player_id_ = from._impl_.player_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GC_MOVE_NOTIFY::CopyFrom(const GC_MOVE_NOTIFY& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.GC_MOVE_NOTIFY)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GC_MOVE_NOTIFY::InternalSwap(GC_MOVE_NOTIFY* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.player_id_)
      + sizeof(GC_MOVE_NOTIFY::_impl_.player_id_)
      - PROTOBUF_FIELD_OFFSET(GC_MOVE_NOTIFY, _impl_.cur_pos_)>(
          reinterpret_cast<char*>(&_impl_.cur_pos_),
          reinterpret_cast<char*>(&other->_impl_.cur_pos_));
}

::google::protobuf::Metadata GC_MOVE_NOTIFY::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CG_LOGIN_REQ::_Internal {
 public:
};

CG_LOGIN_REQ::CG_LOGIN_REQ(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.CG_LOGIN_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CG_LOGIN_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::CG_LOGIN_REQ& from_msg)
      : username_(arena, from.username_),
        _cached_size_{0} {}

CG_LOGIN_REQ::CG_LOGIN_REQ(
    ::google::protobuf::Arena* arena,
    const CG_LOGIN_REQ& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CG_LOGIN_REQ* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:game.CG_LOGIN_REQ)
}
inline PROTOBUF_NDEBUG_INLINE CG_LOGIN_REQ::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : username_(arena),
        _cached_size_{0} {}

inline void CG_LOGIN_REQ::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CG_LOGIN_REQ::~CG_LOGIN_REQ() {
  // @@protoc_insertion_point(destructor:game.CG_LOGIN_REQ)
  SharedDtor(*this);
}
inline void CG_LOGIN_REQ::SharedDtor(MessageLite& self) {
  CG_LOGIN_REQ& this_ = static_cast<CG_LOGIN_REQ&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.username_.Destroy();
  this_._impl_.~Impl_();
}

inline void* CG_LOGIN_REQ::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) CG_LOGIN_REQ(arena);
}
constexpr auto CG_LOGIN_REQ::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CG_LOGIN_REQ),
                                            alignof(CG_LOGIN_REQ));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull CG_LOGIN_REQ::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_CG_LOGIN_REQ_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &CG_LOGIN_REQ::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<CG_LOGIN_REQ>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &CG_LOGIN_REQ::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<CG_LOGIN_REQ>(), &CG_LOGIN_REQ::ByteSizeLong,
            &CG_LOGIN_REQ::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(CG_LOGIN_REQ, _impl_._cached_size_),
        false,
    },
    &CG_LOGIN_REQ::kDescriptorMethods,
    &descriptor_table_game_5fmessages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* CG_LOGIN_REQ::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> CG_LOGIN_REQ::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::CG_LOGIN_REQ>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string username = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(CG_LOGIN_REQ, _impl_.username_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string username = 1;
    {PROTOBUF_FIELD_OFFSET(CG_LOGIN_REQ, _impl_.username_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\21\10\0\0\0\0\0\0"
    "game.CG_LOGIN_REQ"
    "username"
  }},
};

PROTOBUF_NOINLINE void CG_LOGIN_REQ::Clear() {
// @@protoc_insertion_point(message_clear_start:game.CG_LOGIN_REQ)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.username_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* CG_LOGIN_REQ::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const CG_LOGIN_REQ& this_ = static_cast<const CG_LOGIN_REQ&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* CG_LOGIN_REQ::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const CG_LOGIN_REQ& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.CG_LOGIN_REQ)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string username = 1;
          if (!this_._internal_username().empty()) {
            const std::string& _s = this_._internal_username();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "game.CG_LOGIN_REQ.username");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.CG_LOGIN_REQ)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t CG_LOGIN_REQ::ByteSizeLong(const MessageLite& base) {
          const CG_LOGIN_REQ& this_ = static_cast<const CG_LOGIN_REQ&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t CG_LOGIN_REQ::ByteSizeLong() const {
          const CG_LOGIN_REQ& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.CG_LOGIN_REQ)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // string username = 1;
            if (!this_._internal_username().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_username());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void CG_LOGIN_REQ::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CG_LOGIN_REQ*>(&to_msg);
  auto& from = static_cast<const CG_LOGIN_REQ&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:game.CG_LOGIN_REQ)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_username().empty()) {
    _this->_internal_set_username(from._internal_username());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void CG_LOGIN_REQ::CopyFrom(const CG_LOGIN_REQ& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.CG_LOGIN_REQ)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CG_LOGIN_REQ::InternalSwap(CG_LOGIN_REQ* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.username_, &other->_impl_.username_, arena);
}

::google::protobuf::Metadata CG_LOGIN_REQ::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GC_LOGIN_RES::_Internal {
 public:
  using HasBits =
      decltype(std::declval<GC_LOGIN_RES>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_._has_bits_);
};

GC_LOGIN_RES::GC_LOGIN_RES(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:game.GC_LOGIN_RES)
}
inline PROTOBUF_NDEBUG_INLINE GC_LOGIN_RES::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::game::GC_LOGIN_RES& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

GC_LOGIN_RES::GC_LOGIN_RES(
    ::google::protobuf::Arena* arena,
    const GC_LOGIN_RES& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GC_LOGIN_RES* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.spawn_pos_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::game::Pos>(
                              arena, *from._impl_.spawn_pos_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, success_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, success_),
           offsetof(Impl_, player_id_) -
               offsetof(Impl_, success_) +
               sizeof(Impl_::player_id_));

  // @@protoc_insertion_point(copy_constructor:game.GC_LOGIN_RES)
}
inline PROTOBUF_NDEBUG_INLINE GC_LOGIN_RES::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GC_LOGIN_RES::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, spawn_pos_),
           0,
           offsetof(Impl_, player_id_) -
               offsetof(Impl_, spawn_pos_) +
               sizeof(Impl_::player_id_));
}
GC_LOGIN_RES::~GC_LOGIN_RES() {
  // @@protoc_insertion_point(destructor:game.GC_LOGIN_RES)
  SharedDtor(*this);
}
inline void GC_LOGIN_RES::SharedDtor(MessageLite& self) {
  GC_LOGIN_RES& this_ = static_cast<GC_LOGIN_RES&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.spawn_pos_;
  this_._impl_.~Impl_();
}

inline void* GC_LOGIN_RES::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GC_LOGIN_RES(arena);
}
constexpr auto GC_LOGIN_RES::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GC_LOGIN_RES),
                                            alignof(GC_LOGIN_RES));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GC_LOGIN_RES::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GC_LOGIN_RES_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GC_LOGIN_RES::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GC_LOGIN_RES>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GC_LOGIN_RES::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GC_LOGIN_RES>(), &GC_LOGIN_RES::ByteSizeLong,
            &GC_LOGIN_RES::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_._cached_size_),
        false,
    },
    &GC_LOGIN_RES::kDescriptorMethods,
    &descriptor_table_game_5fmessages_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GC_LOGIN_RES::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> GC_LOGIN_RES::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::game::GC_LOGIN_RES>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(GC_LOGIN_RES, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.success_)}},
    // int32 player_id = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(GC_LOGIN_RES, _impl_.player_id_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.player_id_)}},
    // .game.Pos spawn_pos = 3;
    {::_pbi::TcParser::FastMtS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.spawn_pos_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.success_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // int32 player_id = 2;
    {PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.player_id_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // .game.Pos spawn_pos = 3;
    {PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.spawn_pos_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::game::Pos>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void GC_LOGIN_RES::Clear() {
// @@protoc_insertion_point(message_clear_start:game.GC_LOGIN_RES)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.spawn_pos_ != nullptr);
    _impl_.spawn_pos_->Clear();
  }
  ::memset(&_impl_.success_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.player_id_) -
      reinterpret_cast<char*>(&_impl_.success_)) + sizeof(_impl_.player_id_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GC_LOGIN_RES::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GC_LOGIN_RES& this_ = static_cast<const GC_LOGIN_RES&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GC_LOGIN_RES::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GC_LOGIN_RES& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:game.GC_LOGIN_RES)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          // int32 player_id = 2;
          if (this_._internal_player_id() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<2>(
                    stream, this_._internal_player_id(), target);
          }

          cached_has_bits = this_._impl_._has_bits_[0];
          // .game.Pos spawn_pos = 3;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                3, *this_._impl_.spawn_pos_, this_._impl_.spawn_pos_->GetCachedSize(), target,
                stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:game.GC_LOGIN_RES)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GC_LOGIN_RES::ByteSizeLong(const MessageLite& base) {
          const GC_LOGIN_RES& this_ = static_cast<const GC_LOGIN_RES&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GC_LOGIN_RES::ByteSizeLong() const {
          const GC_LOGIN_RES& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:game.GC_LOGIN_RES)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .game.Pos spawn_pos = 3;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.spawn_pos_);
            }
          }
           {
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
            // int32 player_id = 2;
            if (this_._internal_player_id() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_player_id());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GC_LOGIN_RES::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GC_LOGIN_RES*>(&to_msg);
  auto& from = static_cast<const GC_LOGIN_RES&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:game.GC_LOGIN_RES)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.spawn_pos_ != nullptr);
    if (_this->_impl_.spawn_pos_ == nullptr) {
      _this->_impl_.spawn_pos_ =
          ::google::protobuf::Message::CopyConstruct<::game::Pos>(arena, *from._impl_.spawn_pos_);
    } else {
      _this->_impl_.spawn_pos_->MergeFrom(*from._impl_.spawn_pos_);
    }
  }
  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  if (from._internal_player_id() != 0) {
    _this->_impl_.player_id_ = from._impl_.player_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GC_LOGIN_RES::CopyFrom(const GC_LOGIN_RES& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:game.GC_LOGIN_RES)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GC_LOGIN_RES::InternalSwap(GC_LOGIN_RES* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.player_id_)
      + sizeof(GC_LOGIN_RES::_impl_.player_id_)
      - PROTOBUF_FIELD_OFFSET(GC_LOGIN_RES, _impl_.spawn_pos_)>(
          reinterpret_cast<char*>(&_impl_.spawn_pos_),
          reinterpret_cast<char*>(&other->_impl_.spawn_pos_));
}

::google::protobuf::Metadata GC_LOGIN_RES::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace game
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_game_5fmessages_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
